services:
  - type: web
    name: djang0-app
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key:DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
